config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :restaurants
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  mount API::Base, at: "/"
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :rating_n_reviews
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  #before_action :logged_in_user, only: [:show]
  before_action :admin_user,     only: [:new, :create, :update, :destroy]

  def new
    @restaurant = Restaurant.new
  end

  def index
    @restaurants = Restaurant.paginate(page: params[:page])
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @rating_n_reviews = @restaurant.rating_n_reviews.paginate(page: params[:page])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:info] = "Restaurant created successfully."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    Restaurant.find(params[:id]).destroy
    flash[:success] = "Restaurant deleted"
    redirect_to restaurants_url
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :location)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def admin_user
      redirect_to(root_url) unless logged_in? && current_user.admin?
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

  # Returns the Gravatar for the given user.
  def image_for(restaurant, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(restaurant.name.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: restaurant.name, class: "gravatar")
  end
end  

app/views/restaurants/_restaurant.html.erb
<li>
  <%= image_for restaurant, size: 50 %>
  <%= link_to restaurant.name, restaurant %>
  <% if logged_in? && current_user.admin?%>
    | <%= link_to "delete", restaurant, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
  <br><br><br><br>
</li>

app/views/restaurants/index.html.erb
<% provide(:title, 'Restaurants') %>
<h1>Restaurants</h1>

<%= will_paginate %>

<ul class="restaurants">
  <%= render @restaurants %>
</ul>

<%= will_paginate %>
<br style = “line-height:6;”><br>
<% if logged_in? && current_user.admin?%>
  <%= link_to "Add New Restaurant", restaurants_new_path, class: "btn btn-lg btn-primary" %>
<% end %>

app/views/restaurants/new.html.erb
<% provide(:title, 'Add Restaurant') %>
<h1>Add Restaurant</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@restaurant) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= image_for @restaurant %>
        <font size="+3">
        <%= @restaurant.name %>
        </font>
        <br><br>
        <span class='notbold'>
          <%= @restaurant.location %>
        </span>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @restaurant.rating_n_reviews.any? %>
      <h3>Rating And Reviews (<%= @restaurant.rating_n_reviews.count %>)</h3>
      <ol class="rating_n_reviews">
        <%= render @rating_n_reviews %>
      </ol>
      <%= will_paginate @rating_n_reviews %>
    <% end %>
  </div>
</div>